### ISSUE TITLE
Plugin crashing on load

### ISSUE THREAD

**Issue by RiddicTH** [Deckerz/Plugins#3]
I saw a couple other issues get closed due to no logs, so I'm hoping this is the right info here.

Taken from dalamud.log

2022-07-29 05:37:14.890 +01:00 [ERR] [LOCALPLUGIN] Error while loading Blackjack
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void Dalamud.Game.Gui.ChatGui.Enable()'.
   at Blackjack.PluginUi..ctor(Configuration configuration, ChatGui chatGui, ClientState clientState)
   at Blackjack.Plugin..ctor(DalamudPluginInterface pluginInterface, CommandManager commandManager, ChatGui chatGui, ClientState clientState) in C:\Users\decla\RiderProjects\BlackjackPlugin\Blackjack\Plugin.cs:line 27
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 746

If there is a different log file you need an excerpt from, please let me know.

**Comment by Deckerz** [comment]
I have released a testing version if you could give it a go. It should work if not i will be able to test later today or tomorrow.

**Comment by RiddicTH** [comment]
Seems to be returning a new error on the test version

[ERR] [Blackjack] UiBuilder OnBuildUi caught exception
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Blackjack.PluginUi.DrawMainWindow()
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 473

**Comment by Deckerz** [comment]
I built using the wrong .net version. Please try v0.0.0.9

**Comment by RiddicTH** [comment]
Plugin seems to be loading and running fine on 0.0.0.9! Issue resolved. Thank you for your hard work, Love this plugin a lot.

**Comment by Deckerz** [comment]
Thanks for confirming. I will push it as a full update rather than pre-release now
